name: flutter_puzzle_hack
description: Flutter Puzzle Hack Challenge
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  confetti: ^0.6.0
  dart_code_metrics: ^4.9.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  just_audio: ^0.9.18
  logging: ^1.0.2
  rive: ^0.8.1
  universal_platform: ^1.0.0+1

dev_dependencies:
  fake_async: ^1.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/themes/base/
    - assets/themes/base/audio/
    