name: Application Check

on:
  pull_request:
  push:
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - ".github/workflows/check.yml"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.8.1
          channel: stable
          cache: true

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
        
