name: Web Deployment

on:
  push:
    paths:
        - "lib/**"
        - "pubspec.yaml"
        - "pubspec.lock"
        - ".github/workflows/deploy_web.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.8.1
          channel: stable
          cache: true

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Build web version
        run: flutter build web

      - name: Deploy on Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: apparence-flutter-puzzle
          target: apparence-flutter-puzzle
          expires: 30d
          channelId: live
        
